### ISSUE TITLE
ResultTemplate code set方法属性错误

### ISSUE THREAD

**Issue by AgnoyZ** [fengwenyi/api-result#3]
ResultTemplate类中的code的set方法应该是public属性的吧

**Comment by fengwenyi** [comment]
下个版本修复：https://github.com/fengwenyi/api-result/commit/5f74fea356ab47838b240a9f172ab4d69fe5438d#diff-be73cb12373598e60bfd596c6fa91031abf1bbe76284bb23f01fc8021bb7e336
